---
title: "Protocol: Descriptive Analysis of Deprescribing Patterns for People Living with Advanced Chronic Kidney Disease"
date: "2026-06-24"
date-format: "D MMMM YYYY"
author: "Matthew Letts^1,2^, Robert Porteous^1^, Rachel Denholm^1^, Rupert Payne^3^, Jonathan Sterne^1^, Fergus Caskey^2^"
number-sections: true
format:
  gfm:
    toc: false
  docx:
    toc: true
bibliography: references.bib
csl: vancouver.csl
toc: true
---

^1^ Electronic Health Records Group, Population Health Sciences, Bristol Medical School, University of Bristol, Bristol, UK

^2^ Bristol Renal, Population Health Sciences, Bristol Medical School, University of Bristol, Bristol, UK

^3^ Exeter Collaboration for Academic Primary Care, University of Exeter, Exeter, UK

---

| Version | Description | Date |
|---------|-------------|------|
| 1.0 | Initial protocol developed and structured according to RECORD-PE [@Brown2024] | 22/05/2026 |

---

# Background

Ninety-eight percent of people living with chronic kidney disease stages 4 and 5 not receiving kidney replacement therapy - CKD 4/5 - live with multiple long-term conditions [@Hawthorne2023]. Resultantly, polypharmacy is highly prevalent - this group are prescribed on average 8-9 medicines per day (and >100 pills per week) [@vanOosten2021]. Polypharmacy is well linked to avoidable harms such as falls and hospitalisations [@Fried2014] so managing it safely is a key action area within the World Health Organisation's active global patient safety challenge: *Medication Without Harm* [@WHO2023]. For people with CKD 4/5, the risk of medication-related harm is augmented by unpredictable drug handling and excretion - 1 in 5 experience a medication-related harm each year [@Laville2020], making them a high priority group to study [@Mohottige2021]. Added to this, clinical trials that establish the safety and effectiveness of medicines often exclude people living with CKD 4/5, and do not reflect their comorbidity and diversity [@Colombijn2024]. 

Deprescribing - the systematic process of stopping or reducing medicines - is a proposed way of reducing the harms associated with polypharmacy. Within the recently updated KDIGO (Kidney Disease | Improving Global Outcomes) CKD practice guideline there is a new chapter entitled *Medication management and Drug Stewardship*, however this includes an acknowledgment that evidence to guide deprescribing is limited [@Stevens2024]. We have shown that a proportion of people with advanced kidney disease are having medications such as statins discontinued in their last years of life [@Letts2024], but wider-scale information is lacking. Currently there is little guidance for clinicians about what medicines can be deprescribed and when. 

We aim to describe the current patterns of discontinuation of common medicines in people living with advanced CKD in England, and evaluate the clinical and sociodemographic factors that lead to variances in these patterns. In routine healthcare data, deprescribing is largely observable as medication *discontinuation*, which will therefore be the primary focus of this study.

# Objectives

1. To describe patterns of prescribing at a national level for people living with advanced CKD
2. To establish the patterns of discontinuation of medicines in people in England living with advanced CKD.
3. To identify the clinical and sociodemographic factors associated with variances in these patterns.

# Methods

## Study design

We will conduct cross-sectional and longitudinal analyses of a retrospective cohort of individuals living with advanced kidney disease living in England.

## Data sources

We will analyse the primary care record data of people living in England that is stored and managed by The Phoenix Partnership (TPP), specifically through the OpenSAFELY-TPP secure analytical platform. We will utilise OpenSAFELY-TPP's established linkages to:

- Office for National Statistics (ONS) data on registered deaths
- NHS Secondary Uses Service data, which includes information regarding hospital admissions, and is used to derive each individual's ethnicity
- Data on Index of Multiple Deprivation (IMD)

## Study population

This retrospective cohort study will analyse the cohort of individuals living with CKD 4/5 on 01/03/2022 (the **'index date'**), and then follow up their prescriptions for the following 4 years.

### Inclusion criteria

Individuals will be included in the cohort if on the index date they meet all the following criteria:

* Alive
* Aged ≥18 and ≤110 years
* Continuous registration at a single GP practice that uses TPP software for at least the one year prior.
* Evidence of advanced chronic kidney disease, confirmed by the presence of one or both of the following [@Sparks2025]: 
  + The two most recent serum creatinine measurements that are >90 days apart are consistent with an estimated glomerular filtration rate (eGFR) <30 mls/min/1.73m^2^ (calculated using the 2009 CKD-EPI equation as recommended by the [UK Kidney Association](https://www.ukkidney.org/health-professionals/information-resources/uk-eckd-guide/measurement-kidney-function)).
  + A SNOMED code indicating a diagnosis of CKD 4 and 5 ([OpenCodelists](https://www.opencodelists.org/codelist/user/mletts92/chronic-kidney-disease-stage-4-and-5-but-not-receiving-kidney-replacement-therapy/49c071e2/)) on any prior date.


### Exclusion criteria

* People in receipt of kidney replacement therapy (KRT). This is defined as a [code](https://www.opencodelists.org/codelist/opensafely/renal-replacement-therapy/2020-04-14/#full-list) indicating dialysis or transplant prior to the index date, or on the index date itself. This method has been shown to be sensitive for identifying the prevalent KRT population in England [@Santhakumaran2024]. 

### Follow up

Study participants will be followed up from the index date until the earliest of:

- End of maximum follow up period (4 years)
- Death
- Initiation of kidney replacement therapy (dialysis or transplant)
- End of registration with GP practice that uses TPP software

### Data quality assurance criteria

Individuals will only be included if they meet all the following criteria:

- Known sex that is exactly 'male' or 'female'
- Known year of birth
- (Known IMD
- Known ethnicity
- Known STP) - *I'm not sure about these bottom three - they may well exclude people unnecessarily*

## Prescribing information

### Prescribing data

In this analysis we will study baseline prescribing on the index date, and the trends of medication discontinuation over time.

The medication table within OpenSAFELY-TPP contains information for every medication that is prescribed in primary care. Each prescription is recorded using its corresponding NHS dictionary of medicines and devices (dm+d) code and corresponding date. [dm+d codes](https://digital.nhs.uk/data-and-information/information-standards/governance/latest-activity/standards-and-collections/scci0052-dictionary-of-medicines-and-devices-dm-d/) are the preferred mechanism through which medicinal product identification and communication occurs within the NHS. In OpenSAFELY, each dm+d code corresponds to the name (e.g. atorvastatin), strength (e.g. 40mg) and formulation (e.g. tablet) of a prescribed drug. Data on the dosing recommendation (e.g. take 1 tablet once a day), the quantity of a medication prescribed (e.g. 28 tablets), whether a prescription was dispensed, or whether the patient adhered to the medication as prescribed are not available.

### Prescribing data handling

Each dm+d code has one or more official routes of administration and these will be mapped to the study data using publicly available [NHS TRUD](https://isd.digital.nhs.uk/trud/users/guest/filters/0/categories/6) (Technology Reference data Update Distribution) reference files. Each of the 79 official routes of administration will be mapped according to author consensus to one of the following categories: oral, topical, inhaled, eye/ear/nasal, oromucosal, rectal/vaginal, transdermal, intramuscular, intravenous, subcutaneous and other. If a dm+d code has multiple licensed routes it will be classified 'multiple routes', and if no licensed routes, 'unknown'.

Each medication will then have its dm+d code mapped to its corresponding British National Formulary (BNF) substance code using publicly available [mapping data](https://www.nhsbsa.nhs.uk/prescription-data/understanding-our-data/bnf-snomed-mapping). BNF codes follow a clear hierarchical structure and allow for clinically meaningful analysis. 

### Medication inclusion / exclusion criteria
Medicines will be included / excluded in our analysis by considering their *scope, uniqueness and timeframe* [@Goedken2016].

#### Scope
We will include medications based on their drug type and route.

- Drug type. We will include medications within BNF chapters 1 to 13. BNF chapters 14 to 23 will be excluded as they represent specialist products that are unlikely to be common and not targets for discontinuation, and medical devices.
- Route. We will include medications that are orally administered. This is because oral medications are the most likely to be deprescribed in this population.

It will not be possible to distinguish PRN (as required) prescriptions from regular prescriptions, and so all medications will be assumed regular. 

#### Uniqueness
Combination products have distinct dm+d and BNF substance codes and so will be counted as a single drug.

#### Timeframe
Conceptually, for a medicine to be discontinued, it must be first in *chronic* use, i.e. being used on the index date, and regularly prior to that. There is no consensus regarding how to define a chronic prescription within electronic health record data. OpenSAFELY-TPP lacks data to show the clinician-intended duration for each prescription, and therefore assumptions about the length of each prescription are required to establish what a person could have been taking on any given date. It has previously been shown that for five of the commonest medicines, 92% were prescribed for 28 or 56 days, with the remainder being prescribed for 7 or 84 days [@Mackenna2025]. 

Considering this variability, we will define a medication as chronic, and include it in our analyses, if all of the following are true:

* In the 180 days prior to the index date:
  + It is prescribed two or more times (*regular*)
  + There are >=21 days between the oldest and the most recent prescriptions (*sustained*)
* In the 90 days prior to the index date:
  + It is prescribed once or more (*recent*)

## Outcome - medication discontinuation
Medications prescribed at baseline will be followed longitudinally for up to 4 years to examine patterns of discontinuation. 

Within OpenSAFELY-TPP the duration of each prescription is unknown. In line with previous publications [@Bayliss2025], discontinuation will be defined as a gap of a prescription of a chronic medicine of 120 days or more. This will allow a window of time for re-prescription to occur even if the prescription was issued for 84 days (the maximum length in usual practice in England). The date of discontinuation will be defined as the date of the last prescription.

*This needs discussion - could this be operationalised better? We could look at dose reduction, or something more complex modelling prior gaps*

## Covariates
Covariates have been chosen for two different reasons:

- It is hypothesised that they will likely have an impact on medication discontinuation.
- To promote analytical inclusivity, by exploring variations by protected characteristics.

Covariates, which will be defined on the index date, are described in the table below.

+----------------------------+---------------+----------------------------------------------+
| **Covariate**              | **Type**      | **Definition**                               |
+============================+===============+==============================================+
| Age                        | Continuous    | Age in years calculated from year of birth.  |
|                            |               | Will be modelled using splines               |
|                            |               |                                              |
|                            |               | Strata: 18–49, 50–64, 65–74, 75–84, ≥85      |
+----------------------------+---------------+----------------------------------------------+
| Sex                        | Categorical   | Male or female                               |
+----------------------------+---------------+----------------------------------------------+
| Ethnicity                  | Categorical   | Derived from GP record and NHS               |
|                            |               | Secondary Uses Service data, using           |
|                            |               | the most recent non-missing value. Strata:   |
|                            |               |                                              |
|                            |               | White\                                       |
|                            |               | Mixed / Multiple ethnic\                     |
|                            |               | Asian / Asian British\                       |
|                            |               | Black / African / Caribbean / Black British\ |
|                            |               | Other ethnic group\                          | 
|                            |               | Not stated / Not known\                      |
+----------------------------+---------------+----------------------------------------------+
| Deprivation                | Categorical   | Deciles of Index of Multiple Deprivation     |
|                            |               | (IMD) based on address on index date         | 
+----------------------------+---------------+----------------------------------------------+
| eGFR                       | Continuous    | Estimated glomerular filtration rate         |
|                            |               | on the index date, calculated from           |
|                            |               | the most recent serum creatinine             |
|                            |               | using the 2009 CKD-EPI equation              |
+----------------------------+---------------+----------------------------------------------+
| Number of chronic          | Continuous    | Count of distinct included chronic           |
| prescriptions              |               | medications on the index date                |
+----------------------------+---------------+----------------------------------------------+
| Region                     | Categorical   | East of England\                             |
|                            |               | London\                                      | 
|                            |               | Midlands\                                    |
|                            |               | North East and Yorkshire\                    |
|                            |               | North West\                                  |
|                            |               | South East\                                  |
|                            |               | South West\                                  |
+----------------------------+---------------+----------------------------------------------+
| Frailty                    | Categorical   | Characterised using the electronic           |
|                            |               | frailty index (eFI, ideally eFI2             |
|                            |               | [@Best2025]), a widely used metric           |
|                            |               | for identifying frailty in                   |
|                            |               | electronic health records.                   |
|                            |               | This is all tbc - watch the OS Slack         |
|                            |               | Strata: non-frail, mildly frail,             |
|                            |               | moderately frail, severely frail             |
|                            |               | https://github.com/opensafely/covid_collater |
|                            |               | al_hf_update/blob/236c243cf4882e73393761083d |
|                            |               | ee1be2340b8d6a/analysis/eFI_calc_hf.do       |
+----------------------------+---------------+----------------------------------------------+
| Care home status           | Binary        | Using TPP's algorithm to determine if a      |
|                            |               | person is a likely care home resident        |
+----------------------------+---------------+----------------------------------------------+
| Consultation rate          | Continuous    | Number of GP consultations 12 months         |
|                            |               | prior to the index date                      |
+----------------------------+---------------+----------------------------------------------+
| Dementia                   | Binary        | 1 if diagnosis present; 0 otherwise          |
|                            |               | I could try to make this more granular?      |
+----------------------------+---------------+----------------------------------------------+
| Liver disease              | Binary        | 1 if diagnosis present; 0 otherwise          |
+----------------------------+---------------+----------------------------------------------+
| Cancer                     | Categorical   | 1 if diagnosis present; 0 otherwise          |
+----------------------------+---------------+----------------------------------------------+
| Diabetes                   | Binary        | 1 if diagnosis present; 0 otherwise          |
+----------------------------+---------------+----------------------------------------------+
| Cambridge Multimorbidity   | Continuous    | https://github.com/opensafely/               |
| Score                      |               | NeurodegenerativeDiseaseBurden/blob/         |
|                            |               | 33c6a297c0e46a49643890363e4aca9191f87ed0/    |
|                            |               | analysis/dataset_definition/                 |
|                            |               | variable_helper_functions.py#L45-L96         |
+----------------------------+---------------+----------------------------------------------+
| COPD                       | Binary        | 1 if diagnosis present; 0 otherwise          |
+----------------------------+---------------+----------------------------------------------+
| Previous cardiovascular    | Binary        | fill                                         |
| disease                    |               | in                                           |
+----------------------------+---------------+----------------------------------------------+
| Having had another         | Binary        | Is this possible?                            |
| medicine stopped in last   |               |                                              |
| 12 months                  |               |                                              |
+----------------------------+---------------+----------------------------------------------+
| Discharge from a hospital  | Binary        |                                              |
| admission within last 6    |               |                                              |
| months                     |               |                                              |
+----------------------------+---------------+----------------------------------------------+
| The effect of recent       |               |                                              |
| interaction with secondary |               |                                              |
| care                       |               |                                              |
+----------------------------+---------------+----------------------------------------------+
| Something about adverse    |               |                                              |
| effects                    |               |                                              |
+----------------------------+---------------+----------------------------------------------+
| Use drawio to decide rest  |               |                                              |
+----------------------------+---------------+----------------------------------------------+

### Other covariates

+----------------------------+---------------+----------------------------------------------+
| Risk of mortality          | Continuous /  | Estimated 4-year risk of mortality           |
|                            | categorical   | using the CKD G4+ prediction tool            |
|                            |               | [@Grams2018]. This tool is suggested for use |
|                            |               | in the 2024 KDIGO CKD management guideline   |
|                            |               | [@Stevens2024]. It requires 8 variables:     |
|                            |               | Requires: age (30–85),                       |
|                            |               | sex, race (black or white),                  |
|                            |               | proteinuria (uPCR or uACR), smoking          |
|                            |               | status, diabetes status, history of          |
|                            |               | cardiovascular disease, eGFR (15–30),        |
|                            |               | systolic BP (90–180).                        |
|                            |               |                                              |
|                            |               | Strata: <25%, 25–49%, 50–74%, ≥75%           |
+----------------------------+---------------+----------------------------------------------+

## Statistical methods

### Cohort characteristics
We will produce a flowchart to show the numbers of individuals that are included / excluded at each stage of cohort development. Descriptive statistics will be used to describe this group's baseline characteristics: mean, median and measure of variance for continuous variables, and frequencies and proportions for categorical variables. 

### Baseline prescribing
We will present:

1. The average total number of prescribed medications per person on the index date, and
2. The proportions of the population prescribed each of the most common categories of medication (grouped by BNF subchapter).

We will explore the associations between age, sex, ethnicity and deprivation and the total number of prescribed medications on the index date through individual x,y plots and then multivariable Poisson regression (*or negative binomial because prescribing data likely to be overdispersed?*)  

### Medication discontinuation 
Competing events:
 
- Death (all-cause)
- Initiation of kidney replacement therapy

#### Cumulative incidence of discontinuation
For each of the studied medication classes, cumulative incidence functions (CIFs) for medication discontinuation over the follow-up period will be plotted. These will model death and the initiation of KRT as competing events.

Time to first discontinuation event

What about people who start the medication after the index date - i.e. new initiators vs prevalent users?

#### Predictors of discontinuation

### Software
All analyses will be conducted using R. OpenSAFELY analyses control the version of R (4.4.3) and the packages that can be used - and these are publicly available [here](https://github.com/opensafely-core/r-docker/blob/main/v2/packages.md).

### Sensitivity analyses
In sensitivity analyses, we will explore the effect of:

- Including drugs that are administered through other routes.
- Varying the definition of a chronic medicines (using different numbers/timeframes of prescriptions).
- Defining discontinuation using a gap of: ≥30 days, ≥60 days and ≥180 days. 



## Tables and figures

## Study limitations

# Other information

## Funding

## PPIE

# References {.unnumbered}
